language: node_js

node_js:
	- stable

branch:
	except: 
		- gh-pages

script:
 	-npm run build --prod

deploy:
	provider: pages
	skip_cleanup: true
	github_token: $GH_TOKEN
on:
	branch: master

local_dir: dist
